import fs from "node:fs";
import path from "node:path";

export const GENERATED_PATH = "src/platform/registry/generated.ts";
export const APPS_DIR = "src/apps";

/** Discovers src/apps/<id>/manifest.ts and emits generated.ts source. */
export function generateRegistrySource(appsDir: string = APPS_DIR): string {
  const ids = fs.existsSync(appsDir)
    ? fs
        .readdirSync(appsDir, { withFileTypes: true })
        .filter(
          (d) =>
            d.isDirectory() &&
            fs.existsSync(path.join(appsDir, d.name, "manifest.ts")),
        )
        .map((d) => d.name)
        .sort()
    : [];

  const imports = ids
    .map((id, i) => `import manifest${i} from "../../apps/${id}/manifest";`)
    .join("\n");
  const list = ids.map((_, i) => `manifest${i}`).join(", ");

  return `// Generated by scripts/gen-registry.ts — do not edit.
// Server-only: policies are functions; never import this from client components.
import type { AppManifest } from "./types";
${imports}
export const manifests: AppManifest[] = [${list}];
`;
}

/**
 * Regenerates generated.ts unconditionally so seed/e2e never see a stale
 * registry when a manifest was added or removed since the last run.
 * (Scripts run outside Next's pre-hooks, and npm pre-hooks only fire via
 * `npm run` — this also covers direct `tsx` and test invocations.)
 */
export function ensureRegistry(
  appsDir: string = APPS_DIR,
  outPath: string = GENERATED_PATH,
): void {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, generateRegistrySource(appsDir));
}
