import fs from "node:fs";
import path from "node:path";

export const GENERATED_PATH = "src/platform/registry/generated.ts";
export const APPS_DIR = "src/apps";

/** Discovers src/apps/<id>/manifest.ts and emits generated.ts source. */
export function generateRegistrySource(appsDir: string = APPS_DIR): string {
  const ids = fs.existsSync(appsDir)
    ? fs
        .readdirSync(appsDir, { withFileTypes: true })
        .filter(
          (d) =>
            d.isDirectory() &&
            fs.existsSync(path.join(appsDir, d.name, "manifest.ts")),
        )
        .map((d) => d.name)
        .sort()
    : [];

  const imports = ids
    .map((id, i) => `import manifest${i} from "../../apps/${id}/manifest";`)
    .join("\n");
  const list = ids.map((_, i) => `manifest${i}`).join(", ");

  return `// Generated by scripts/gen-registry.ts — do not edit.
// Server-only: policies are functions; never import this from client components.
import type { AppManifest } from "./types";
${imports}
export const manifests: AppManifest[] = [${list}];
`;
}

/** Writes generated.ts if missing (scripts run outside Next's pre-hooks). */
export function ensureRegistry(): void {
  if (!fs.existsSync(GENERATED_PATH)) {
    fs.mkdirSync(path.dirname(GENERATED_PATH), { recursive: true });
    fs.writeFileSync(GENERATED_PATH, generateRegistrySource());
  }
}
